# Generated by Django 5.0.1 on 2024-07-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='Contact Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('image', models.ImageField(upload_to='services/')),
                ('short_content', models.TextField(verbose_name='Short Content')),
                ('long_content', models.TextField(verbose_name='Long Content')),
                ('url_name', models.CharField(max_length=50, unique=True, verbose_name='URL Name')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
